apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mqtt-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mqtt
  endpoints:
  - port: mqtt-port
    interval: 30s
    path: /metrics