apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-prometheus-metrics.fullname" . }}
  labels:
    {{- include "mqtt-prometheus-metrics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mqtt-prometheus-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mqtt-prometheus-metrics.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mqtt-prometheus-metrics
            - secretRef:
                name: mqtt-prometheus-metrics
          env:
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-prometheus-metrics
                  key: MQTT_PASSWORD
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mqtt-prometheus-metrics
                  key: MQTT_USERNAME
            - name: MQTT_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: mqtt-prometheus-metrics
                  key: MQTT_BROKER_URL
