{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mqtt-prometheus-metrics.fullname" . }}
  labels:
    {{- include "mqtt-prometheus-metrics.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "mqtt-prometheus-metrics.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
      metricRelabelings:
        - action: labeldrop
          regex: {{ .Values.serviceMonitor.dropLabels }}

{{- end }}
