on:
  push:
    branches:
      - main
#    paths:
#      - 'Containerfile'

jobs:
  build:
    # Build the container with podman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: Containerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: cr.dbyron.net/mqtt-prometheus-metrics:1.0.4

